image: redrock-fe
variables:
  REPO_NAME: cyxbs-bms

stages:
  - setup
  - build
  - deploy

prepare:
  stage: setup
  tags:
    - redrock-fe
  cache: 
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
  script:
    - npm ci
  only:
    changes:
      - package-lock.json

build:
  stage: build
  tags:
    - redrock-fe
  cache: 
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
    policy: pull
  script:
    - npm run build
  artifacts:
    expire_in: 3 days
    paths:
      - build

deploy_dev:
  stage: deploy
  tags:
    - redrock-fe
  script:
    - tar -C build -cf dist.tar .
    - curl -F data=@dist.tar -X POST http://202.202.43.234/rrapi/deploy/node/$REPO_NAME
